# Generated by Django 2.1.5 on 2020-08-31 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flightAircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=10)),
                ('aircraft_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='flightNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='flightSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=10, null=True)),
                ('arrival', models.CharField(max_length=10, null=True)),
                ('flight_time', models.DateTimeField()),
                ('daytogo', models.DateField()),
                ('comingDay', models.DateField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 8, 31, 12, 16, 7, 390634, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_season_price', models.ForeignKey(on_delete=True, related_name='cost2', to='reservation_api.flightSection')),
                ('peak_season_price', models.ForeignKey(on_delete=True, related_name='cost1', to='reservation_api.flightSection')),
            ],
        ),
        migrations.CreateModel(
            name='seatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(max_length=10)),
            ],
        ),
    ]
