# Generated by Django 2.1.5 on 2020-09-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flightAircraft',
        ),
        migrations.DeleteModel(
            name='flightNumber',
        ),
        migrations.RemoveField(
            model_name='price',
            name='low_season_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='peak_season_price',
        ),
        migrations.DeleteModel(
            name='seatClass',
        ),
        migrations.DeleteModel(
            name='flightSection',
        ),
        migrations.DeleteModel(
            name='price',
        ),
    ]
