# Generated by Django 2.1.5 on 2020-10-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeachEngine',
            new_name='SearchEngine',
        ),
    ]
