FROM digglerz/python3.8

MAINTAINER dhdiagram@gmail.com
EXPOSE 9001
WORKDIR /app
ADD . /app
RUN pip3 install djangorestframework
RUN pip3 install pymysql
RUN pip3 install Django==3.1.1
RUN pip3 install requests
RUN python3 manage.py migrate
RUN python3 manage.py makemigrations
CMD ["python3" ,"manage.py", "runserver", "0.0.0.0:9001"]