# Generated by Django 2.1.5 on 2020-07-17 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 57, 35, 504034, tzinfo=utc)),
        ),
    ]
