# Generated by Django 2.1.5 on 2020-08-09 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200809_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 8, 21, 16, 17359, tzinfo=utc)),
        ),
    ]
