# Generated by Django 2.1.5 on 2020-08-09 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200809_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 8, 34, 16, 882234, tzinfo=utc)),
        ),
    ]
