# Generated by Django 2.1.5 on 2020-08-11 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20200809_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 11, 26, 50, 12046, tzinfo=utc)),
        ),
    ]
