# Generated by Django 2.1.5 on 2020-08-11 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20200811_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 11, 38, 7, 595358, tzinfo=utc)),
        ),
    ]
