# Generated by Django 2.1.5 on 2020-08-11 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20200811_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 11, 48, 57, 485301, tzinfo=utc)),
        ),
    ]
