# Generated by Django 2.1.5 on 2020-08-13 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_auto_20200813_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 11, 12, 33, 626465, tzinfo=utc)),
        ),
    ]
