# Generated by Django 2.1.5 on 2020-08-13 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_auto_20200813_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 12, 7, 50, 906054, tzinfo=utc)),
        ),
    ]
