# Generated by Django 2.1.5 on 2020-08-25 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_auto_20200813_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 12, 29, 47, 712092, tzinfo=utc)),
        ),
    ]
