# Generated by Django 2.1.5 on 2020-08-31 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_auto_20200829_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 12, 16, 7, 382395, tzinfo=utc)),
        ),
    ]
