# Generated by Django 2.1.5 on 2020-09-06 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_auto_20200831_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 12, 16, 10, 853607, tzinfo=utc)),
        ),
    ]
