# Generated by Django 2.1.5 on 2020-09-11 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_auto_20200906_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 10, 22, 41, 502299, tzinfo=utc)),
        ),
    ]
